In [2]:
import large_image
import os
import sys
sys.path.append(os.path.join(os.getcwd()))

In [3]:
import os

import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

#Some nice default configuration for plots
plt.rcParams['figure.figsize'] = 10, 10
plt.rcParams['image.cmap'] = 'gray'

In [4]:
wsi_url = 'https://data.kitware.com/api/v1/file/5899dd6d8d777f07219fcb23/download'

wsi_path = 'TCGA-02-0010-01Z-00-DX4.07de2e55-a8fe-40ee-9e98-bcb78050b9f7.svs'

if not os.path.isfile(wsi_path):
    !curl -OJ "$wsi_url"

In [5]:
ts = large_image.getTileSource('TCGA-02-0010-01Z-00-DX4.07de2e55-a8fe-40ee-9e98-bcb78050b9f7.svs')

In [6]:
ts.getNativeMagnification()

{'magnification': 20.0, 'mm_x': 0.0005015, 'mm_y': 0.0005015}

In [8]:
import pprint
for tile_info in ts.tileIterator(
    tile_size=dict(width=1024, height=1024),
        tile_overlap=dict(x=256, y=256, edges=False)
):
    pprint.pprint(tile_info['tile_overlap'])
    var = tile_info['tile_overlap']
    #break    

{'bottom': 128, 'left': 0, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top': 0}
{'bottom': 128, 'left': 128, 'right': 128, 'top'

In [69]:
def overlap_image(im_label=np.zeros(1024, 1024), overlap=128, l=False, r=False, t=False, b=False):
    print(l, r, t, b)
    im_label_del = np.zeros_like(im_label)

    if np.any(im_label):

        im_border_mask = np.zeros_like(im_label)
        if l:
            im_border_mask[:overlap, :] = 1
        if r:
            im_border_mask[-overlap:, :] = 1
        if t:
            im_border_mask[:, :overlap] = 1
        if b:
            im_border_mask[:, -overlap:] = 1

        # simplified logic
        if np.any(im_label):
            im_border_mask = np.zeros_like(im_label)
            im_border_mask[:overlap, :] = int(l)
            im_border_mask[-overlap:, :] = int(r)
            im_border_mask[:, :overlap] = int(t)
            im_border_mask[:, -overlap:] = int(b)

        border_indices = np.unique(im_label[im_border_mask > 0])
        border_indices = border_indices[border_indices > 0]

        if len(border_indices) == 0:
            return im_label

        # im_label_del = condense(delete(im_label, border_indices))

    return im_label_del

In [71]:

for tile_info in ts.tileIterator(
        tile_size=dict(width=1024, height=1024),
        tile_overlap=dict(x=128, y=128)):
    # get all the required parameters
    x_max = tile_info['iterator_range']['level_x_max']
    y_max = tile_info['iterator_range']['level_y_max']
    curr_x = tile_info['tile_position']['level_x']
    curr_y = tile_info['tile_position']['level_y']

    if curr_x == curr_y == 0:
        print('top left corner', curr_x, curr_y)
        overlap_image()

    if (curr_x != 0 and curr_x != x_max-1) and curr_y == 0:
        print('first row cases', curr_x, curr_y)
        overlap_image(l=True)

    if curr_x == x_max-1 and curr_y == 0:
        print('top right corner', curr_x, curr_y)
        overlap_image(l=True)

    if curr_x == 0 and curr_y == y_max-1:
        print('bottom left corner', curr_x, curr_y)
        overlap_image(t=True)

    if curr_x == x_max-1 and curr_y == y_max-1:
        print('bottom right corner', curr_x, curr_y)
        overlap_image(t=True, l=True)

    if curr_x == 0 and (curr_y != 0 and curr_y != y_max-1):
        print('first column cases', curr_x, curr_y)
        overlap_image(t=True)

    if curr_x == x_max-1 and (curr_y != 0 and curr_y != y_max-1):
        print('last column cases', curr_x, curr_y)
        overlap_image(t=True, l=True)

    if (curr_x != 0 and curr_x != x_max-1) and curr_y == y_max-1:
        print('last row case', curr_x, curr_y)
        overlap_image(t=True, l=True)

    if (curr_x != 0 and curr_x != x_max-1) and (curr_y != 0 and curr_y != y_max-1):
        print('in between cases', curr_x, curr_y)
        overlap_image(t=True, l=True)

top left corner 0 0
False False False False
first row cases 1 0
True False False False
first row cases 2 0
True False False False
first row cases 3 0
True False False False
first row cases 4 0
True False False False
first row cases 5 0
True False False False
first row cases 6 0
True False False False
first row cases 7 0
True False False False
first row cases 8 0
True False False False
first row cases 9 0
True False False False
first row cases 10 0
True False False False
first row cases 11 0
True False False False
first row cases 12 0
True False False False
first row cases 13 0
True False False False
first row cases 14 0
True False False False
first row cases 15 0
True False False False
first row cases 16 0
True False False False
first row cases 17 0
True False False False
first row cases 18 0
True False False False
first row cases 19 0
True False False False
first row cases 20 0
True False False False
first row cases 21 0
True False False False
first row cases 22 0
True False False Fal

In [72]:
# improved func
for tile_info in ts.tileIterator(
        tile_size=dict(width=1024, height=1024),
        tile_overlap=dict(x=128, y=128)):
    # get all the required parameters
    x_max = tile_info['iterator_range']['level_x_max']
    y_max = tile_info['iterator_range']['level_y_max']
    curr_x = tile_info['tile_position']['level_x']
    curr_y = tile_info['tile_position']['level_y']

    if curr_x == 0 and curr_y == 0:
        print('top left corner', curr_x, curr_y)
        overlap_image()

    elif curr_x == x_max-1 and curr_y == 0:
        print('top right corner', curr_x, curr_y)
        overlap_image(l=True)

    elif curr_x == 0 and curr_y == y_max-1:
        print('bottom left corner', curr_x, curr_y)
        overlap_image(t=True)

    elif curr_x == x_max-1 and curr_y == y_max-1:
        print('bottom right corner', curr_x, curr_y)
        overlap_image(t=True, l=True)

    elif curr_x == 0:
        print('first column cases', curr_x, curr_y)
        overlap_image(t=True)

    elif curr_x == x_max-1:
        print('last column cases', curr_x, curr_y)
        overlap_image(t=True, l=True)

    elif curr_y == 0:
        print('first row cases', curr_x, curr_y)
        overlap_image(l=True)

    elif curr_y == y_max-1:
        print('last row case', curr_x, curr_y)
        overlap_image(t=True, l=True)

    else:
        print('in between cases', curr_x, curr_y)
        overlap_image(t=True, l=True)

top left corner 0 0
False False False False
first row cases 1 0
True False False False
first row cases 2 0
True False False False
first row cases 3 0
True False False False
first row cases 4 0
True False False False
first row cases 5 0
True False False False
first row cases 6 0
True False False False
first row cases 7 0
True False False False
first row cases 8 0
True False False False
first row cases 9 0
True False False False
first row cases 10 0
True False False False
first row cases 11 0
True False False False
first row cases 12 0
True False False False
first row cases 13 0
True False False False
first row cases 14 0
True False False False
first row cases 15 0
True False False False
first row cases 16 0
True False False False
first row cases 17 0
True False False False
first row cases 18 0
True False False False
first row cases 19 0
True False False False
first row cases 20 0
True False False False
first row cases 21 0
True False False False
first row cases 22 0
True False False Fal

In [41]:
a, b = 0, 5

In [40]:
np.any(a,b)

False

In [42]:
5 < 6 or 3

True

In [43]:
0//2

0

In [57]:
a = np.zeros((10,10))

In [58]:
a[:,:2] = True
a

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
a[:,-2:] = True
a

array([[1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.]])

In [53]:
a[:2,:] = True
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.]])

In [54]:
a[-2:,:] = True
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])